export const LOGIN_SUCCESS = 'login_success';//登陆成功
export const ERR_MSG = 'err_msg';//错误信息提示
export const RECEIVE_NEWS = 'receive_news';//接收资讯
export const USER_INFO = 'user_info';//用户信息
export const MY_COURSE = 'my_course';//我的课程
export const ALL_COURSE = 'all_course';//查看所有课程
export const ALL_DISCUSS = 'all_discuss';//所有讨论
export const THE_DISCUSS = 'the_discuss';//某一讨论
export const ALL_TEACHER = 'all_teacher';//所有老师
export const THE_TEACHER = 'the_teacher';//某一老师
export const THE_TEACHER_COURSE = 'the_teacher_course';//某一老师的课程
export const COURSE_DETAIL = 'course_detail';//某一课程详情
export const COURE_REVIEW = 'course_review'; //课程评价
export const STU_LIST = 'stu_list';
export const FEEDBACK = 'feedback';//反馈
